### ISSUE TITLE
Make panoc_algo modular

### ISSUE THREAD

**Issue by alphaville** [kul-forbes/EmbeddedMPC#10]
Make `panoc_algo` modular and unit-test the individual components: e.g., remove the linesearch to a different function and test it.

**Comment by AjSat** [comment]
Is the current modular structure alright?

**Comment by alphaville** [comment]
The level of modularity of the code is now fine, but the structures `panoc_work` and `panoc_point` need to be documented because it is not clear what their fields correspond to.
