### ISSUE TITLE
Memory management errors

### ISSUE THREAD

**Issue by alphaville** [kul-forbes/EmbeddedMPC#4]
Valgrind found 131470 errors among which there are errors because of uninitialized values, invalid reads, invalid writes, non-freed memory and more.

Detailed log: [valgrind-log-full.txt](https://github.com/kul-forbes/EmbeddedMPC/files/1207690/valgrind-log-full.txt)

**Comment by alphaville** [comment]
Have memory issues been resolved now? Should we close this issue?

**Comment by AjSat** [comment]
Yes the memory issues are resolved now.
